<a href="https://colab.research.google.com/github/Shanzakhan786/data_tpye_-inpython.ipynb/blob/main/lectures_03_Attributes_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **AWFERA _LMS**

# **Lecture No # 03 Practices**

# **Coures: Machine Learning**

# **Topic: Attributes **

**This notebook cover the following concept:**

**1. Pandas**

**2. Loading the data**

**3. Data Frame**

# **Key Features of Pandas**
**DataFrame:** A two-dimensional labeled data structure for working with tabular data.

**Data Manipulation:** Powerful tools for filtering, transforming, and aggregating data.

**Data Cleaning:** Functions to handle missing values, duplicate data, and outliers.

**Data Input/Output:** Read and write data from various file formats, including CSV and Excel.

# **1.Installing Pandas**

Run the command: !pip install pandas.

In [4]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# **1.1. Importing the installed Libraries**

In [5]:
import pandas as pd

# **1.2. Loading the document**

In [6]:
df = pd.read_csv('/content/vgsalesGlobale.csv')

# **2. Data Exploration**

# **2.1. Displaying the Top Rows of the Data**

# The **head()** function is used to display the first few rows of a DataFrame or a data structure containing tabular data.

It is primarily used for data exploration and getting a quick overview of the data.

In [7]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

# **2.2. Displaying the Last rows on the data**

# The **tail()** function is used to view the last few rows of a DataFrame or a file.

It is a convenient way to quickly inspect the end of a dataset or file without having to display the entire contents.

In [10]:
df.tail(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16588,16591,Mega Brain Boost,DS,2008.0,Puzzle,Majesco Entertainment,0.01,0.00,0.00,0.0,0.01
16589,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016.0,Action,dramatic create,0.00,0.00,0.01,0.0,0.01
16590,16593,Eiyuu Densetsu: Sora no Kiseki Material Collec...,PSP,2007.0,Role-Playing,Falcom Corporation,0.00,0.00,0.01,0.0,0.01
16591,16594,Myst IV: Revelation,PC,2004.0,Adventure,Ubisoft,0.01,0.00,0.00,0.0,0.01
16592,16595,Plushees,DS,2008.0,Simulation,Destineer,0.01,0.00,0.00,0.0,0.01
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.0,0.01

### **2.3. Shape of the Data**


In pandas, the **.shape** attribute is used to determine the dimensions of a DataFrame or Series. It returns a tuple containing the number of rows and columns present in the

## **2.4. Data types in dataset**

In pandas, the **.dtype** function is used to determine the data type of a Series(one dimesional) or DataFrame. It returns the data type of the elements within the object.

In [12]:
df.shape

(16598, 11)

In [15]:
print("Data type of each column")
print(df.dtypes)

Data type of each column
Rank              int64
Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [18]:
x=df[["NA_Sales"]] #Here means we are returning dataframe [[]] double square bracket means series of data

In [19]:
x=df["NA_Sales"]